# Generated by Django 3.2.4 on 2021-06-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubmedID', models.TextField()),
                ('title', models.TextField()),
                ('pubDate', models.DateField()),
                ('abstract', models.TextField()),
                ('doi', models.URLField()),
                ('keywords', models.TextField()),
                ('authors', models.TextField()),
                ('tags', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('surname', models.TextField(default='SURNAME')),
            ],
        ),
    ]
